require("user.options")
require("user.keymaps")
require("user.autocmds")
require("user.colorscheme")

require("user.lsp")

require("user.plugins")

require("user.plugins.autopairs")
require("user.plugins.copilot")
require("user.plugins.goto-preview")
require("user.plugins.dressing")
require("user.plugins.fidget")
require("user.plugins.harpoon")
require("user.plugins.cmp")
require("user.plugins.startup")
require("user.plugins.comment")
require("user.plugins.chatgpt")
require("user.plugins.nvim-tree")
require("user.plugins.telescope")
require("user.plugins.treesitter")
require("user.plugins.trouble")
require("user.plugins.toggleterm")
require("user.plugins.which-key")
require("user.plugins.lualine")
require("user.plugins.gitsigns")
require("user.plugins.zen-mode")
require("user.plugins.leap")
